name: CI/CD Nightly + SCA

on:
  schedule:
    - cron: '55 20 * * *'
      timezone: America/La_Paz
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scans:
    name: Security scans (${{ github.event_name }})
    uses: ./.github/workflows/security-scans.yml
    with:
      run_dependency_check: true
    secrets: inherit
